apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: rohitergurala/visionmysql
      context: ../visionmysql
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
